# Generated by Django 5.1.6 on 2025-02-18 13:55

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
